PlanejadorFerias/Models/Colaboradores.cs
namespace PlanejadorFerias.Models
{
    public class Colaboradores
    {
        public Guid Id { get; set; }
        public string Nome { get; set; }
        public string Cargo { get; set; }
        public string Setor { get; set;}
        public DateTime DataAdmissao { get; set;}

        public Colaboradores() { }
    }
}

PlanejadorFerias/Models/ErrorViewModel.cs
namespace PlanejadorFerias.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PlanejadorFerias/Controllers/ColaboradoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PlanejadorFerias.Data;
using PlanejadorFerias.Models;

namespace PlanejadorFerias.Controllers
{
    public class ColaboradoresController : Controller
    {
        private readonly PlanejadorFeriasContext _context;

        public ColaboradoresController(PlanejadorFeriasContext context)
        {
            _context = context;
        }

        // GET: Colaboradores
        public async Task<IActionResult> Index()
        {
            return _context.Colaboradores != null ?
                        View(await _context.Colaboradores.ToListAsync()) :
                          Problem("Entity set 'PlanejadorFeriasContext.Colaboradores'  is null.");
        }

        // GET: Colaboradores/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Colaboradores == null)
            {
                return NotFound();
            }

            var colaboradores = await _context.Colaboradores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (colaboradores == null)
            {
                return NotFound();
            }

            return View(colaboradores);
        }

        // GET: Colaboradores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Colaboradores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Cargo,Setor,DataAdmissao")] Colaboradores colaboradores)
        {
            if (ModelState.IsValid)
            {
                colaboradores.Id = Guid.NewGuid();
                _context.Add(colaboradores);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(colaboradores);
        }

        // GET: Colaboradores/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Colaboradores == null)
            {
                return NotFound();
            }

            var colaboradores = await _context.Colaboradores.FindAsync(id);
            if (colaboradores == null)
            {
                return NotFound();
            }
            return View(colaboradores);
        }

        // POST: Colaboradores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Nome,Cargo,Setor,DataAdmissao")] Colaboradores colaboradores)
        {
            if (id != colaboradores.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(colaboradores);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ColaboradoresExists(colaboradores.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(colaboradores);
        }

        // GET: Colaboradores/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Colaboradores == null)
            {
                return NotFound();

            }

            var colaboradores = await _context.Colaboradores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (colaboradores == null)
            {
                return NotFound();
            }

            return View(colaboradores);
        }

        // POST: Colaboradores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Colaboradores == null)
            {
                return Problem("Entity set 'PlanejadorFeriasContext.Colaboradores'  is null.");
            }
            var colaboradores = await _context.Colaboradores.FindAsync(id);
            if (colaboradores != null)
            {
                _context.Colaboradores.Remove(colaboradores);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ColaboradoresExists(Guid id)
        {
          return (_context.Colaboradores?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

PlanejadorFerias/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PlanejadorFerias.Models;
using System.Diagnostics;

namespace PlanejadorFerias.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PlanejadorFerias/Views/Colaboradores/Create.cshtml
@model PlanejadorFerias.Models.Colaboradores

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Colaboradores</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cargo" class="control-label"></label>
                <input asp-for="Cargo" class="form-control" />
                <span asp-validation-for="Cargo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Setor" class="control-label"></label>
                <input asp-for="Setor" class="form-control" />
                <span asp-validation-for="Setor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataAdmissao" class="control-label"></label>
                <input asp-for="DataAdmissao" class="form-control" />
                <span asp-validation-for="DataAdmissao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PlanejadorFerias/Views/Colaboradores/Delete.cshtml
@model PlanejadorFerias.Models.Colaboradores

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Colaboradores</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cargo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cargo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Setor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Setor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataAdmissao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataAdmissao)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PlanejadorFerias/Views/Colaboradores/Details.cshtml
@model PlanejadorFerias.Models.Colaboradores

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Colaboradores</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cargo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cargo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Setor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Setor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataAdmissao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataAdmissao)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PlanejadorFerias/Views/Colaboradores/Edit.cshtml
@model PlanejadorFerias.Models.Colaboradores

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Colaboradores</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cargo" class="control-label"></label>
                <input asp-for="Cargo" class="form-control" />
                <span asp-validation-for="Cargo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Setor" class="control-label"></label>
                <input asp-for="Setor" class="form-control" />
                <span asp-validation-for="Setor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataAdmissao" class="control-label"></label>
                <input asp-for="DataAdmissao" class="form-control" />
                <span asp-validation-for="DataAdmissao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PlanejadorFerias/Views/Colaboradores/Index.cshtml
@model IEnumerable<PlanejadorFerias.Models.Colaboradores>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table table-striped table-dark">
    <thead>
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cargo)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Setor)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.DataAdmissao)
            </th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td scope="row">
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
                <td scope ="row">
                @Html.DisplayFor(modelItem => item.Cargo)
            </td>
            <td scope="row">
                @Html.DisplayFor(modelItem => item.Setor)
            </td>
            <td scope="row">
                @Html.DisplayFor(modelItem => item.DataAdmissao)
            </td>
            <td scope="row">
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

PlanejadorFerias/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PlanejadorFerias/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PlanejadorFerias</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PlanejadorFerias.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PlanejadorFerias</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Colaboradores" asp-action="Create">Administrativo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PlanejadorFerias - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>